Name: wepApp

services:
  db:
    image: mysql:8.0.3
    volumes:
      - db_data: /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql

  api:
    depends_on:
      - db
    image: evanhighvolt/mon_api_img
    ports:
      - "9000:80"
    restart: on-failure

    working_dir: /var/lib/api

  web_app:
    depends_on:
      - api
    image: evanhighvolt/webapp_img
    ports:
      - "9001:9001"
    restart: always

    working_dir: /var/www/html
volumes:
  db_data: